---
steps:
- name: gcr.io/nhsy-0002/terraform-validator:latest
  dir: deployments/app1/dev
  args:
  - init
- name: gcr.io/nhsy-0002/terraform-validator:latest
  dir: deployments/app1/dev
  args:
  - plan
  - -out=terraform.tfplan
- name: gcr.io/nhsy-0002/terraform-validator:latest
  dir: deployments/app1/dev
  args:
  - convert
  - terraform.tfplan
- name: gcr.io/nhsy-0002/terraform-validator:latest
  dir: deployments/app1/dev
  args:
  - validate
  - terraform.tfplan
  -  --policy-path=../../../policy-library/
